name = "aiken-lang/domswap"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/domswap'"

[repository]
user = "aiken-lang"
project = "domswap"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
